# Project information
site_name: شاززز گاید
site_url: https://guide.shaazzz.ir
site_author: Shaazzz
site_description: شاززز گاید

# Copyright
copyright: |
  تمامی مطالب این وب‌سایت تحت پروانه
  <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" style="color: #4ab6f1">CC-BY-SA</a>
  در دسترس است.

# Configuration
theme:
  name: material
  language: fa
  direction: rtl
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - search.highlight
    - toc.follow
    - navigation.instant

  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Vazirmatn
    code: Source Code Pro

  logo: assets/images/sid.png
  favicon: "assets/images/sid.png"

# Plugins
plugins:
  - search
  
# Customization
extra:
  social:
    - icon: material/web
      link: https://shaazzz.ir
      name: وب‌سایت
    - icon: fontawesome/brands/github
      link: https://github.com/shaazzz
      name: گیت‌هاب
    - icon: fontawesome/brands/telegram
      link: https://t.me/shaazzz
      name: تلگرام

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/mathjax/polyfill.min.js
  - javascripts/mathjax/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# auto-generated by nav.py
# don't write "ANYTHING" after this section
nav:
  - شازززگاید: index.md
  - سطح ۱:
    - مقدمه: Level1/intro.md
    - پیاده سازی: Level1/implementation.md
    - توابع بازگشتی: Level1/recursive.md
    - عملیات های بیتی: Level1/bitmask.md
    - باینری سرچ: Level1/binary_search.md
    - Two Pointers: Level1/two_pointers.md
    - پریفیکس سام: Level1/prefix_sum.md
    - الگوریتم های حریصانه: Level1/greedy.md
    - تقسیم و حل: Level1/divide.md
    - مرتب سازی: Level1/sort.md
  - سطح ۲:
    - Coming soon...: coming_soon.md
  - سطح ۳:
    - Coming soon...: coming_soon.md
  - سطح ۴:
    - Coming soon...: coming_soon.md
  - سطح ۵:
    - Coming soon...: coming_soon.md
  - سطح ۶:
    - Coming soon...: coming_soon.md
  - سطح ۷:
    - Coming soon...: coming_soon.md
  - همه سوالات: problemset.md
